"""Generate independent retrieval queries directly from raw markdown papers.

Queries generated by this script are not derived from any graph/hypergraph
candidate evidence. They are sentence-level experimental claims mined from the
raw corpus, intended for retrieval qrels annotation.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timezone
import json
import re
from pathlib import Path
from typing import Any


METRIC_TERMS = [
    "coulombic efficiency", "voltage efficiency", "energy efficiency", "ce", "ve", "ee",
    "capacity retention", "capacity fade", "capacity fading", "decay rate",
    "area resistance", "area-specific resistance", "ohmic resistance",
    "charge-transfer resistance", "energy density", "power density",
    "permeability", "crossover", "selectivity", "conductivity",
]

CONDITION_TERMS = [
    "current density", "temperature", "flow rate", "concentration", "ph",
    "cycle", "cycles", "mA cm", "mA/cm", "mol l", "mol/l", "c-rate",
]

MATERIAL_TERMS = [
    "nafion", "membrane", "pbi", "speek", "sptpc", "graphite felt",
    "carbon felt", "activated carbon", "electrode", "electrolyte",
    "vanadium", "vos", "h2so4", "hcl", "bismuth", "bi3", "zinc",
    "bromine", "tempo", "viologen", "quinone", "phenazine", "flow battery",
    "redox flow battery", "vrfb", "icrfb", "iron-chromium",
]

MECHANISM_TERMS = [
    "degradation", "crossover", "dendrite", "passivation", "hydrogen evolution",
    "her", "oxygen evolution", "oer", "capacity fading", "side reaction",
    "imbalance", "polarization", "mass transfer", "precipitation",
]

COMPARISON_TERMS = [
    "higher than", "lower than", "compared with", "compared to", "whereas",
    "while", "respectively", "versus", "vs.", "in contrast",
]

UNIT_PATTERN = re.compile(
    r"\b\d+(?:\.\d+)?\s*(?:%|mA\s*(?:/|\s*)cm\s*-?2|A\s*(?:/|\s*)cm\s*-?2|mol\s*(?:/|\s*)L|mmol\s*(?:/|\s*)g|mL\s*(?:/|\s*)min|°C|C|K|cycles?|cm2\s*/\s*s|ohm\s*cm2|S\s*cm-?1)\b",
    flags=re.IGNORECASE,
)


def normalize(text: Any) -> str:
    value = str(text or "").lower()
    replacements = {
        "cm−2": "cm2",
        "cm-2": "cm2",
        "cm^2": "cm2",
        "cm²": "cm2",
        "ω": "ohm",
        "·": " ",
        "–": "-",
        "—": "-",
        "（": "(",
        "）": ")",
    }
    for old, new in replacements.items():
        value = value.replace(old, new)
    value = re.sub(r"\s+", " ", value)
    return value.strip()


def clean_markdown(text: str) -> str:
    text = re.split(
        r"(?:^|\n)\s*(?:#{1,6}\s*)?(?:references|reference|bibliography|acknowledg(?:e)?ments?)\s*(?:\n|$)",
        text,
        maxsplit=1,
        flags=re.IGNORECASE,
    )[0]
    text = re.sub(r"!\[[^\]]*\]\([^)]+\)", " ", text)
    text = re.sub(r"\[[^\]]+\]\([^)]+\)", " ", text)
    text = re.sub(r"`[^`]+`", " ", text)
    text = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\|", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text


def split_sentences(text: str) -> list[str]:
    text = clean_markdown(text)
    pieces = re.split(r"(?<=[.!?。])\s+(?=[A-Z0-9(])", text)
    sentences = []
    for item in pieces:
        sentence = item.strip()
        if 80 <= len(sentence) <= 850:
            sentences.append(sentence)
    return sentences


def contains_any(norm: str, terms: list[str]) -> bool:
    for term in terms:
        if len(term) <= 3 and term.isalnum():
            if re.search(rf"\b{re.escape(term)}\b", norm, flags=re.IGNORECASE):
                return True
        elif term in norm:
            return True
    return False


def fact_type(sentence: str) -> str:
    norm = normalize(sentence)
    if contains_any(norm, COMPARISON_TERMS):
        return "COMPARISON"
    if contains_any(norm, MECHANISM_TERMS):
        return "DEGRADATION_OR_MECHANISM"
    if contains_any(norm, METRIC_TERMS) and contains_any(norm, CONDITION_TERMS):
        return "OPERATION_PERFORMANCE"
    if contains_any(norm, MATERIAL_TERMS) and any(x in norm for x in ["prepared", "modified", "doped", "coated", "composite", "membrane"]):
        return "COMPOSITION"
    if contains_any(norm, METRIC_TERMS):
        return "MEASUREMENT"
    return "BACKGROUND_FACT"


def score_sentence(sentence: str) -> float:
    norm = normalize(sentence)
    reject_terms = [
        "doi:", "doi.org", "https://doi", "http://", "https://", "www.",
        "copyright", "biography", "finalist", "received her",
        "received his", "earned her", "earned his", "postdoc", "professor",
        "university of", "research interests include", "has filed more than",
        "career", "awards", "department of",
    ]
    if any(term in norm for term in reject_terms):
        return -10.0
    if re.search(r"\[\s*\d+\s*\].{0,160}(?:doi|https|journal|chem|energy|electrochim)", sentence, flags=re.IGNORECASE):
        return -10.0
    if len(re.findall(r"\b[A-Z]\.", sentence)) >= 4:
        return -10.0
    score = 0.0
    score += 2.0 if UNIT_PATTERN.search(sentence) else 0.0
    score += 1.5 if contains_any(norm, METRIC_TERMS) else 0.0
    score += 1.2 if contains_any(norm, CONDITION_TERMS) else 0.0
    score += 1.0 if contains_any(norm, MATERIAL_TERMS) else 0.0
    score += 1.0 if contains_any(norm, MECHANISM_TERMS) else 0.0
    score += 0.8 if contains_any(norm, COMPARISON_TERMS) else 0.0
    flow_or_experiment = contains_any(
        norm,
        [
            "flow battery",
            "redox flow",
            "vrfb",
            "icrfb",
            "vanadium",
            "nafion",
            "graphite felt",
            "carbon felt",
            "current density",
            "capacity retention",
            "coulombic efficiency",
            "voltage efficiency",
            "energy efficiency",
            "area resistance",
            "permeability",
            "crossover",
            "mol/l",
            "ma/cm2",
        ],
    )
    if not flow_or_experiment:
        score -= 2.0
    return score


def extract_entities(sentence: str) -> list[str]:
    found = []
    lower = normalize(sentence)
    phrase_patterns = [
        r"\bNafion\s*\d+\b",
        r"\bSNPBI[-\w.]*\b",
        r"\bSPTPC[-\w.]*\b",
        r"\bSPEEK(?:/[A-Z]+)?\b",
        r"\bPBI\b",
        r"\bgraphite felt\b",
        r"\bcarbon felt\b",
        r"\bactivated carbon felt\b",
        r"\bVRFB\b",
        r"\bICRFB\b",
        r"\biron[- ]chromium redox flow battery\b",
        r"\bvanadium redox flow battery\b",
        r"\bzinc[- ]bromine flow battery\b",
        r"\bVOSO4\b",
        r"\bH2SO4\b",
        r"\bHCl\b",
        r"\bBi(?:3\+|Cl3)?\b",
        r"\bCr\([IIIV]+\)\b",
        r"\bV\([IIIV]+\)\b",
        r"\bTEMPO\b",
        r"\bviologen\b",
        r"\bquinone\b",
    ]
    for pattern in phrase_patterns:
        for match in re.findall(pattern, sentence, flags=re.IGNORECASE):
            found.append(match)
    for term in MATERIAL_TERMS:
        if term in lower:
            found.append(term)
    return list(dict.fromkeys(str(x).strip() for x in found if str(x).strip()))[:12]


def extract_conditions(sentence: str) -> list[dict[str, Any]]:
    conditions = []
    patterns = [
        ("current_density", r"(\d+(?:\.\d+)?)\s*mA\s*(?:/|\s*)cm\s*-?2", "mA/cm2"),
        ("temperature", r"(\d+(?:\.\d+)?)\s*(?:°C|C)\b", "C"),
        ("concentration", r"(\d+(?:\.\d+)?)\s*mol\s*(?:/|\s*)L", "mol/L"),
        ("flow_rate", r"(\d+(?:\.\d+)?)\s*mL\s*(?:/|\s*)min", "mL/min"),
        ("cycle_number", r"(\d+(?:\.\d+)?)\s*cycles?\b", "cycles"),
    ]
    for quantity_type, pattern, unit in patterns:
        for value in re.findall(pattern, sentence, flags=re.IGNORECASE):
            conditions.append({"quantity_type": quantity_type, "value": float(value), "unit": unit})
    return conditions[:8]


def extract_metrics(sentence: str) -> list[dict[str, Any]]:
    metrics = []
    lower = normalize(sentence)
    percent_patterns = [
        ("coulombic efficiency", r"(?:CE|coulombic efficiency)[^\d]{0,30}(\d+(?:\.\d+)?)\s*%"),
        ("voltage efficiency", r"(?:VE|voltage efficiency)[^\d]{0,30}(\d+(?:\.\d+)?)\s*%"),
        ("energy efficiency", r"(?:EE|energy efficiency)[^\d]{0,30}(\d+(?:\.\d+)?)\s*%"),
        ("capacity retention", r"(?:capacity retention|retaining|retained)[^\d]{0,30}(\d+(?:\.\d+)?)\s*%"),
    ]
    for metric_type, pattern in percent_patterns:
        for value in re.findall(pattern, sentence, flags=re.IGNORECASE):
            metrics.append({"metric_type": metric_type, "value": float(value), "unit": "%"})
    if "area resistance" in lower or "area-specific resistance" in lower:
        for value in re.findall(r"(\d+(?:\.\d+)?)\s*ohm\s*cm2", sentence, flags=re.IGNORECASE):
            metrics.append({"metric_type": "area resistance", "value": float(value), "unit": "ohm cm2"})
    if "permeability" in lower or "crossover coefficient" in lower:
        for value in re.findall(r"(\d+(?:\.\d+)?)\s*(?:x|×)\s*10\^?-?(\d+)\s*cm2\s*/\s*s", sentence, flags=re.IGNORECASE):
            base, exp = value
            metrics.append({"metric_type": "permeability/crossover coefficient", "value": f"{base}e-{exp}", "unit": "cm2/s"})
    return metrics[:8]


def make_question(claim: str, ftype: str, doc_id: str) -> str:
    if ftype == "COMPARISON":
        return f"Which evidence in {doc_id} supports this comparison: {claim}"
    if ftype == "OPERATION_PERFORMANCE":
        return f"Which evidence in {doc_id} supports this operation-performance fact: {claim}"
    if ftype == "DEGRADATION_OR_MECHANISM":
        return f"Which evidence in {doc_id} supports this degradation or mechanism claim: {claim}"
    if ftype == "COMPOSITION":
        return f"Which evidence in {doc_id} supports this material composition/design claim: {claim}"
    if ftype == "MEASUREMENT":
        return f"Which evidence in {doc_id} supports this measured property: {claim}"
    return f"Which evidence in {doc_id} supports this literature fact: {claim}"


def generate_queries(input_dir: Path, *, per_doc: int, max_queries: int) -> list[dict[str, Any]]:
    all_queries = []
    per_doc_candidates: dict[str, list[tuple[float, str]]] = defaultdict(list)
    for index, path in enumerate(sorted(input_dir.glob("*.md")), start=1):
        doc_id = f"RFB_{index:03d}"
        for sentence in split_sentences(path.read_text(encoding="utf-8", errors="replace")):
            score = score_sentence(sentence)
            if score >= 2.5:
                per_doc_candidates[doc_id].append((score, sentence))
    for doc_id in sorted(per_doc_candidates):
        ranked = sorted(per_doc_candidates[doc_id], key=lambda pair: (pair[0], len(pair[1])), reverse=True)
        used_claims = set()
        count = 0
        for score, sentence in ranked:
            claim = sentence.strip()
            claim_key = normalize(claim[:220])
            if claim_key in used_claims:
                continue
            used_claims.add(claim_key)
            ftype = fact_type(claim)
            query_number = len(all_queries) + 1
            all_queries.append(
                {
                    "query_id": f"QRAW-{doc_id}-{count + 1:03d}",
                    "question": make_question(claim, ftype, doc_id),
                    "source_doc_id": doc_id,
                    "source_file": f"{int(doc_id.split('_')[-1]):03d}_full.md",
                    "gold_claim": claim,
                    "fact_type": ftype,
                    "difficulty": "raw_sentence",
                    "required_entities": extract_entities(claim),
                    "required_conditions": extract_conditions(claim),
                    "required_metrics": extract_metrics(claim),
                    "required_mechanisms": [term for term in MECHANISM_TERMS if term in normalize(claim)][:8],
                    "generation_source": "raw_markdown_sentence",
                    "raw_sentence_score": round(score, 3),
                    "query_order": query_number,
                }
            )
            count += 1
            if count >= per_doc or len(all_queries) >= max_queries:
                break
        if len(all_queries) >= max_queries:
            break
    return all_queries


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate independent retrieval queries from raw markdown.")
    parser.add_argument("--input-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--per-doc", type=int, default=8)
    parser.add_argument("--max-queries", type=int, default=80)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    queries = generate_queries(args.input_dir, per_doc=args.per_doc, max_queries=args.max_queries)
    result = {
        "metadata": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generation_method": "raw_markdown_sentence_mining_v1",
            "input_dir": str(args.input_dir),
            "num_queries": len(queries),
            "note": "Queries are generated directly from raw markdown sentences, not from graph/hypergraph evidence.",
        },
        "queries": queries,
    }
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({"output": str(args.output), "queries": len(queries)}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
